sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - build-essential
      - aria2
      - lib32stdc++6
      - lib32z1
      - lib32bz2-1.0
      - ninja-build

cache:
  - apt
  - ccache

notifications:
  irc:
#    channels:
#      - secure: "anmDihJ1uPnDSNDsEe3WQ5o4BsPApJbw6NupsAebt6kBxJm7WYKrSyUVmu/9GXgFvy756HBDVA6eikPtcak1+jLFfyOZqGw3ei69ZNnA+R7aoAzfiXilFqf53Yy2tzydEnF2nBYhJjQZgMBZUVWUD6pdKSXtVg/VZRhVqiDlb+A="
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository_slug}:%{branch} - %{message} %{build_url}"

matrix:
  include:
    - os: linux
      compiler: "gcc"
      env: BUILD_TARGET=Linux
    - os: linux
      compiler: "clang"
      env: BUILD_TARGET=Linux
    - os: linux
      compiler: "clang arm64-v8a"
      env: BUILD_TARGET=Android
           BUILD_ARCH=arm64-v8a
    - os: linux
      compiler: "clang armeabi-v7a"
      env: BUILD_TARGET=Android
           BUILD_ARCH=armeabi-v7a
    - os: linux
      compiler: "clang x86"
      env: BUILD_TARGET=Android
           BUILD_ARCH=x86
    - os: linux
      compiler: "clang x86_64"
      env: BUILD_TARGET=Android
           BUILD_ARCH=x86_64
    - os: osx
      osx_image: xcode8.2
      compiler: "clang"
      env: BUILD_TARGET=macOS
    - os: osx
      osx_image: xcode8.2
      compiler: "clang iOS"
      env: BUILD_TARGET=iOS

before_install:
  - bash travis.sh travis_before_install

install:
  - bash travis.sh travis_install

script:
  - bash travis.sh travis_script

after_success:
  - bash travis.sh travis_after_success
