_add_boost_lib(
  NAME unit_test_framework
  SOURCES
    ${boost_SOURCE_DIR}/libs/test/src/compiler_log_formatter.cpp
    ${boost_SOURCE_DIR}/libs/test/src/debug.cpp
    ${boost_SOURCE_DIR}/libs/test/src/decorator.cpp
    ${boost_SOURCE_DIR}/libs/test/src/execution_monitor.cpp
    ${boost_SOURCE_DIR}/libs/test/src/framework.cpp
    ${boost_SOURCE_DIR}/libs/test/src/junit_log_formatter.cpp
    ${boost_SOURCE_DIR}/libs/test/src/plain_report_formatter.cpp
    ${boost_SOURCE_DIR}/libs/test/src/progress_monitor.cpp
    ${boost_SOURCE_DIR}/libs/test/src/results_collector.cpp
    ${boost_SOURCE_DIR}/libs/test/src/results_reporter.cpp
    ${boost_SOURCE_DIR}/libs/test/src/test_framework_init_observer.cpp
    ${boost_SOURCE_DIR}/libs/test/src/test_tools.cpp
    ${boost_SOURCE_DIR}/libs/test/src/test_tree.cpp
    ${boost_SOURCE_DIR}/libs/test/src/unit_test_log.cpp
    ${boost_SOURCE_DIR}/libs/test/src/unit_test_main.cpp
    ${boost_SOURCE_DIR}/libs/test/src/unit_test_monitor.cpp
    ${boost_SOURCE_DIR}/libs/test/src/unit_test_parameters.cpp
    ${boost_SOURCE_DIR}/libs/test/src/xml_log_formatter.cpp
    ${boost_SOURCE_DIR}/libs/test/src/xml_report_formatter.cpp
  LINK
    Boost::timer
)
