_add_boost_lib(
  NAME wave
  SOURCES
    ${boost_SOURCE_DIR}/libs/wave/src/cpplexer/re2clex/aq.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/cpplexer/re2clex/cpp_re.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/instantiate_cpp_exprgrammar.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/instantiate_cpp_grammar.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/instantiate_cpp_literalgrs.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/instantiate_defined_grammar.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/instantiate_predef_macros.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/instantiate_re2c_lexer.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/instantiate_re2c_lexer_str.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/token_ids.cpp
    ${boost_SOURCE_DIR}/libs/wave/src/wave_config_constant.cpp
  LINK
    Boost::date_time
    Boost::filesystem
    Boost::thread
)
